version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/processed:/app/processed
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/frontend.Dockerfile
    ports:
      - "3000:80"
    restart: always
